# Provided list of mentor names
mentor_names = [
    'Aakriti Jaluria COE Mentor F23',
    'Abhay Bagla COE Mentor F23',
    'Abhijay Duggal COE Mentor F23',
    'Abhinav Gupta ECE Mentor F23',
    'Aditi Sinha COE Mentor F23',
    'Aditya Misra COE Mentor F23',
    'Adrija Sengupta COE Mentor F23',
    'Akarsh Srivastava COE Mentor F23',
    'Ananya Bhardwaj ECE Mentor F23',
    'Anuj Pathak COE Mentor F23',
    'Anoushka Duggal COE Mentor F23',
    'Ansh Gupta MEE Mentor F23',
    'Anmol Deep Kaur ENC Mentor F23',
    'Anushka Tiwari ENC Mentor F23',
    'Apaar Mehta CIE Mentor F23',
    'Apoorv Yadav ECE Mentor F23',
    'Arpit Goel CSBS Mentor F23',
    'Charvi Aggarwal TSLAS Mentor F23',
    'Daksh Sharma COE Mentor F23',
    'Deepit Garg ENC Mentor F23',
    'Devansh Verma COE Mentor F23',
    'Diya Wadhawan TSLAS Mentor F23',
    'Hritish Mahajan CSBS Mentor F23',
    'Ishaan Kumar ECE Mentor F23',
    'Ishaana Ali ECE Mentor F23',
    'Jiya Kumar CHE Mentor F23',
    'Jai Raj Singh Ahluwalia CIE Mentor F23',
    'Jasnoor Singh COPC Mentor F23',
    'Ketan Maini COPC Mentor F23',
    'Khushi Yadav EEC Mentor F23',
    'Kirti Bhat BIOTECH Mentor F23',
    'Kriti Goyal BIOTECH Mentor F23',
    'Kshitiz Arora ENC Mentor F23',
    'Maanvi Bansal ELE Mentor F23',
    'Manveen Mann COE Mentor F23',
    'Mehakpreet Kaur COPC Mentor F23',
    'Muskan Bhatia ECE Mentor F23',
    'Naman Arora ECE Mentor F23',
    'Navansh Krishna Goswami ENC Mentor F23',
    'Navyaa Gupta COE Mentor F23',
    'Nipun Jain COE Mentor F23',
    'Nusaibul Hasan EIC Mentor F23',
    'Ojas Kumar Singh COE Mentor F23',
    'Pancham Agarwal COE Mentor F23',
    'Parth Kaushish COE Mentor F23',
    'Parv Narula ECE Mentor F23',
    'Priyal Sharma COE Mentor F23',
    'Praneeth Simon Katta COPC Mentor F23',
    'Prisha Sharma COE Mentor F23',
    'Poorvi Pratap BIOTECH Mentor F23',
    'Prachi Choudhary BIOTECH Mentor F23',
    'Pranay Mathur COE Mentor F23',
    'Riya Goel BIOTECH Mentor F23',
    'Sakshi Rana ENC Mentor F23',
    'Shaurya D Verma COE Mentor F23',
    'Shivam Kumar ECE Mentor F23',
    'Shivansh Verma COPC Mentor F23',
    'Shreya Gakhar CSBS Mentor F23',
    'Sia Duggal ECE Mentor F23',
    'Soham Bhardwaj BIOTECH Mentor F23',
    'Somil Kumar COE Mentor F23',
    'Somya Bansal COE Mentor F23',
    'Suryanshu Anand ENC Mentor F23',
    'Swapnil Chhibber COE Mentor F23',
    'Utkarsh Agarwal CSBS Mentor F23',
    'Vanya Kohli TSLAS Mentor F23',
    'Yashik Garg COPC Mentor F23',
    'Yashika Garg TSLAS Mentor F23'
]

# Provided list of file names
file_names = [
    '2A2CFE74-1030-4CAE-A710-1A4DE2B74BC3-SomilKumar.jpeg',
    '5C819E57-6603-4845-A553-B987BE1FE324-KritiGoyal.jpeg',
    '9BFF8F78-2052-4CDA-BA86-029143CA8216-IshaanaAli.jpeg',
    'AbhayBagla_ComputerEngineering-AbhayBagla.jpg',
    'Abhijay_Duggal_COE-AbhijayDuggal.jpeg',
    'AbhinavGupta_ECE-AbhinavGupta.jpeg',
    'Aditi_COE-AditiSinha.JPG',
    'adityamisra_coe-AdityaMisra.jpg',
    'Akarsh_Srivastava-removebg-preview-AkarshSrivastava.png',
    'Anmol_ENC-AnmolDeepKaur.png',
    'AnujPathak.jpeg',
    'AnushkaTIwari_ENC-AnushkaTiwari.PNG',
    'Apoorv_ECE-ApoorvYadav.JPG',
    'AtharvaPareek_ComputerEngineering-min-AtharvaPareek.JPG',
    'CharviAggarwal_TSLAS-CHARVIAGGARWAL.jpg',
    'DevanshVerma_COE-DevanshVerma.JPG',
    'DocScanner4Jul202311-44am-SomyaBansal.pdf',
    'DSC_0022-SuryanshuAnand.jpeg',
    'F213FEBC-FB45-4617-8901-B52671EF1522-PriyalSharma.jpeg',
    'FE58C2F3-36FF-4E00-8894-822E629E8972-PanchamAgarwal.jpeg',
    'FullSizeRender-ParthKaushish.jpeg',
    'IMG-20221217-WA0028~2-ArpitGoel.jpg',
    'IMG-20230212-WA0174-RiyaGoel.jpg',
    'IMG-20230530-WA0013-PranayMathur.jpg',
    'IMG-20230704-WA0061-AnveshikaGupta.jpg',
    'IMG-20230704-WA0062-Ananta.jpg',
    'IMG-20230704-WA0094-AakritiJaluria.jpg',
    'IMG-20230706-WA0015-AnshGupta.jpg',
    'IMG20220917163211-ISHAANKUMAR.jpg',
    'IMG20230628144814-BhavneetKaur.jpg',
    'IMG_20211111_185152-AryanArpanSingh.jpg',
